import { compileMDX } from "next-mdx-remote/rsc";
import remarkGfm from "remark-gfm";
import remarkBreaks from "remark-breaks";

import rehypeSlug from "rehype-slug";
import rehypeAutolinkHeadings from "rehype-autolink-headings";
import rehypePrettyCode from "rehype-pretty-code";

import Image from "next/image";
import Link from "next/link";

const prettyCodeOptions = {
    theme: "github-dark-default",
    keepBackground: false,
};

const mdxComponents = {
    /*
    |--------------------------------------------------------------------------
    | Headings
    |--------------------------------------------------------------------------
    */

    h1: ({ children, id }) => (
        <h1
            id={id}
            className="
        mb-8
        mt-0
        scroll-mt-28
        text-4xl
        font-bold
        leading-[1.1]
        tracking-tight
        text-slate-950
        md:text-5xl
        lg:text-6xl
      "
        >
            {children}
        </h1>
    ),

    h2: ({ children, id }) => (
        <h2
            id={id}
            className="
        mb-5
        mt-16
        scroll-mt-28
        text-3xl
        font-bold
        leading-tight
        tracking-tight
        text-slate-950
        md:text-4xl
      "
        >
            {children}
        </h2>
    ),

    h3: ({ children, id }) => (
        <h3
            id={id}
            className="
        mb-4
        mt-10
        scroll-mt-28
        text-2xl
        font-semibold
        leading-tight
        text-slate-900
        md:text-3xl
      "
        >
            {children}
        </h3>
    ),

    h4: ({ children, id }) => (
        <h4
            id={id}
            className="
        mb-3
        mt-8
        scroll-mt-28
        text-xl
        font-semibold
        leading-tight
        text-slate-900
        md:text-2xl
      "
        >
            {children}
        </h4>
    ),

    h5: ({ children, id }) => (
        <h5
            id={id}
            className="
        mb-3
        mt-6
        text-lg
        font-semibold
        text-slate-900
        md:text-xl
      "
        >
            {children}
        </h5>
    ),

    h6: ({ children, id }) => (
        <h6
            id={id}
            className="
        mb-2
        mt-6
        text-base
        font-semibold
        uppercase
        tracking-wide
        text-slate-700
      "
        >
            {children}
        </h6>
    ),

    /*
    |--------------------------------------------------------------------------
    | Paragraphs
    |--------------------------------------------------------------------------
    */

    p: ({ children }) => (
        <p
            className="
        mb-6
        text-[17px]
        leading-8
        text-slate-700
        md:text-lg
        md:leading-8
      "
        >
            {children}
        </p>
    ),

    /*
    |--------------------------------------------------------------------------
    | Links
    |--------------------------------------------------------------------------
    */

    a: ({ href = "", children, ...props }) => {
        /*
         * Heading anchors generated by rehype-autolink-headings
         * should NOT look like normal article links.
         */
        if (href.startsWith("#")) {
            return (
                <a
                    href={href}
                    className="no-underline text-inherit"
                    {...props}
                >
                    {children}
                </a>
            );
        }

        const external =
            href.startsWith("http://") ||
            href.startsWith("https://");

        if (external) {
            return (
                <a
                    href={href}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="
            font-medium
            text-primary
            underline
            underline-offset-4
            transition-opacity
            hover:opacity-80
          "
                    {...props}
                >
                    {children}
                </a>
            );
        }

        return (
            <Link
                href={href}
                className="
          font-medium
          text-primary
          underline
          underline-offset-4
          transition-opacity
          hover:opacity-80
        "
                {...props}
            >
                {children}
            </Link>
        );
    },

    /*
    |--------------------------------------------------------------------------
    | Images
    |--------------------------------------------------------------------------
    */

    img: ({ alt = "", ...props }) => (
        <Image
            alt={alt}
            width={1200}
            height={675}
            className="my-8 h-auto w-full rounded-2xl"
            sizes="100vw"
            {...props}
        />
    ),

    /*
    |--------------------------------------------------------------------------
    | Lists
    |--------------------------------------------------------------------------
    */

    ul: ({ children }) => (
        <ul
            className="
        mb-8
        ml-6
        list-disc
        space-y-3
        text-[17px]
        leading-8
        text-slate-700
        md:text-lg
      "
        >
            {children}
        </ul>
    ),

    ol: ({ children }) => (
        <ol
            className="
        mb-8
        ml-6
        list-decimal
        space-y-3
        text-[17px]
        leading-8
        text-slate-700
        md:text-lg
      "
        >
            {children}
        </ol>
    ),

    li: ({ children }) => (
        <li className="pl-2">
            {children}
        </li>
    ),

    /*
    |--------------------------------------------------------------------------
    | Text
    |--------------------------------------------------------------------------
    */

    strong: ({ children }) => (
        <strong className="font-semibold text-slate-950">
            {children}
        </strong>
    ),

    em: ({ children }) => (
        <em className="italic text-slate-800">
            {children}
        </em>
    ),

    /*
    |--------------------------------------------------------------------------
    | Blockquote
    |--------------------------------------------------------------------------
    */

    blockquote: (props) => (
        <blockquote
            className="
        my-8
        border-l-4
        border-primary
        bg-slate-50
        px-6
        py-4
        italic
        text-slate-600
      "
            {...props}
        />
    ),

    /*
    |--------------------------------------------------------------------------
    | Horizontal Rule
    |--------------------------------------------------------------------------
    */

    hr: () => (
        <hr className="my-12 border-slate-200" />
    ),

    /*
    |--------------------------------------------------------------------------
    | Tables
    |--------------------------------------------------------------------------
    */

    table: ({ children, ...props }) => (
        <div className="my-8 overflow-x-auto">
            <table
                className="
          w-full
          border-collapse
          text-left
          text-[16px]
        "
                {...props}
            >
                {children}
            </table>
        </div>
    ),

    thead: ({ children }) => (
        <thead className="bg-slate-100">
            {children}
        </thead>
    ),

    tbody: ({ children }) => (
        <tbody>
            {children}
        </tbody>
    ),

    tr: ({ children }) => (
        <tr className="border-b border-slate-200">
            {children}
        </tr>
    ),

    th: (props) => (
        <th
            className="
        border
        border-slate-300
        bg-slate-100
        px-4
        py-3
        text-left
        font-semibold
        text-slate-900
      "
            {...props}
        />
    ),

    td: (props) => (
        <td
            className="
        border
        border-slate-300
        px-4
        py-3
        text-slate-700
      "
            {...props}
        />
    ),

    /*
    |--------------------------------------------------------------------------
    | Code
    |--------------------------------------------------------------------------
    */

    pre: (props) => (
        <pre
            className="
        my-8
        overflow-x-auto
        rounded-2xl
      "
            {...props}
        />
    ),

    code: (props) => (
        <code {...props} />
    ),
};

export async function parseMDX(source) {
    const { content, frontmatter } = await compileMDX({
        source,

        options: {
            parseFrontmatter: true,

            mdxOptions: {
                remarkPlugins: [
                    remarkGfm,
                    remarkBreaks,
                ],

                rehypePlugins: [
                    rehypeSlug,

                    [
                        rehypeAutolinkHeadings,
                        {
                            behavior: "wrap",
                        },
                    ],

                    [
                        rehypePrettyCode,
                        prettyCodeOptions,
                    ],
                ],
            },
        },

        components: mdxComponents,
    });

    return {
        content,
        frontmatter,
    };
}

export { mdxComponents };   